MT#7335 Fix socket.h/ucast.c conflict when compiling for Debian/jessie
Fails when compiling against Debian/jessie with:

| ucast.c: In function 'HB_make_send_sock':
| ucast.c:466:6: error: conflicting types for 'i'
|   int i = 1;
|       ^

As noted in #713662 "in the current /usr/include/asm-generic/socket.h both macros are defined",
patch also taken from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=713662